name: Bug Report
description: Something isn't working right
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting, please run `zg report` and attach the generated file.
        It collects all the system info, version, logs, and traces we need to debug.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe what went wrong and what you expected.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: |
        What command or request caused the issue?
        Include the curl command, client config, or steps to trigger it.
      placeholder: |
        curl -s http://localhost:8741/v1/chat/completions \
          -H "Content-Type: application/json" \
          -d '{"model":"gemini-3-flash","messages":[{"role":"user","content":"..."}]}'

  - type: textarea
    id: report
    attributes:
      label: Diagnostic Report
      description: |
        Run `zg report` and paste the output here, or attach the file
        (`~/.config/zerogravity/diagnostic.toon`).
      render: text
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Anything else -- screenshots, network setup (VPN/proxy), error messages from your client, etc.
