name: Bug Report
description: Something isn't working right
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Trace ID required for request failures / 请求失败必须提供 Trace ID**

        If a specific request failed, you **must** include `zg report <trace-id>`.
        Use `zg trace ls` to find the trace ID, then run `zg report <trace-id>` to create
        a `.tar.gz` bundle with the full request/response data.

        **Issues without a trace ID for request failures will not be prioritized.**

        ---

        如果某个请求失败，**必须**附上 `zg report <trace-id>` 的输出。
        使用 `zg trace ls` 查找 trace ID，然后运行 `zg report <trace-id>` 生成
        包含完整请求/响应数据的 `.tar.gz` 包。

        **未提供 trace ID 的请求失败 issue 将不会被优先处理。**

  - type: textarea
    id: description
    attributes:
      label: What happened? / 发生了什么？
      description: Describe what went wrong and what you expected.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce / 如何复现
      description: |
        What command or request caused the issue?
        Include the curl command, client config, or steps to trigger it.
      placeholder: |
        curl -s http://localhost:8741/v1/chat/completions \
          -H "Content-Type: application/json" \
          -d '{"model":"gemini-3-flash","messages":[{"role":"user","content":"..."}]}'

  - type: textarea
    id: report
    attributes:
      label: Diagnostic Report / 诊断报告
      description: |
        **For request failures**: Run `zg report <trace-id>` and attach the `.tar.gz` file.
        **For general issues**: Run `zg report` and paste the output here.

        对于请求失败：运行 `zg report <trace-id>` 并附上 `.tar.gz` 文件。
        对于一般问题：运行 `zg report` 并粘贴输出。
      render: text
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Context / 补充信息
      description: Anything else -- screenshots, network setup (VPN/proxy), error messages from your client, etc.
